// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJVF3dlTLSdb3HsABPePJqxOTWRsLGHnk',
    appId: '1:861421481825:web:711cbe23cd97bf5fe21f20',
    messagingSenderId: '861421481825',
    projectId: 'pager-b20dd',
    authDomain: 'pager-b20dd.firebaseapp.com',
    storageBucket: 'pager-b20dd.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQdkeOR2IpZC7lIWaXmNPl0DWq9e1HgjI',
    appId: '1:861421481825:android:e8c27bf8c6e145c4e21f20',
    messagingSenderId: '861421481825',
    projectId: 'pager-b20dd',
    storageBucket: 'pager-b20dd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRDkaeNRQM1En5EFzWQ78RpgFc5OogM5I',
    appId: '1:861421481825:ios:7deeff47e04b5a5ce21f20',
    messagingSenderId: '861421481825',
    projectId: 'pager-b20dd',
    storageBucket: 'pager-b20dd.firebasestorage.app',
    iosBundleId: 'com.example.pager',
  );
}
